### ISSUE TITLE
Subdomonster continued

### ISSUE THREAD

**Issue by thesavant42** [thesavant42/wabax#763]
## Key Issues Noted

1. **Input Box is Squashed & Double Scroll Bars:**
   - The text input for subdomains is not behaving like the one on the index page. It's squashed, possibly due to CSS conflicts, parent container sizing, or flex/grid misconfiguration.
   - Double scroll bars on the right suggest that both the body and a parent container are set to `overflow: auto` or `scroll`.

2. **Tag Input Box is Empty but Shows a Scrollbar:**
   - This usually happens if the input or its wrapper has a fixed height or `overflow: auto` but the internal content or padding is mismatched.

3. **Icons Overlap Resize Handles:**
   - If icons are absolutely positioned or inside flex containers with improper `z-index` or padding, they can cover up the resizable column handles.

4. **Index Page is the Desired Reference:**
   - The index page has a clean, single-row text input, no redundant scroll bars, and properly accessible resize handles.

---

### 1. **Match the Input Box to Index Page**
- Copy the relevant HTML/CSS for the subdomain input from `index.htm` to the subdomonster template.
- Make sure the element is a single-line `<input type="text">` or a `<textarea rows="1">` with `resize: none` if you want to prevent resizing.
- Compare the parent container’s CSS (`display`, `flex`, `width`, `height`, etc.) between the index page and subdomonster.

### 2. **Remove Double Scroll Bars**
- Check CSS for both `.body`, `.main`, and any container wrapping the subdomonster tool. Only one should control vertical scrolling.
- Remove unnecessary `overflow: auto` from parent containers.
- Inspect with browser dev tools: see which containers have scroll and why.

### 3. **Fix Tag Input Scrollbar**
- If the tag input is empty but shows a scroll, inspect its computed CSS for `min-height`, `height`, and `overflow`.
- Remove or adjust `overflow` properties, or set `overflow: hidden` if no scroll is needed.

### 4. **Make Resize Handles Accessible**
- Ensure that icons inside table headers or columns have enough spacing from the edge.
- Use `padding-right` on the header cell to give space for the resize handle.
- Avoid absolutely-positioned icons near the right edge unless necessary, and set a lower `z-index` if they overlap important UI elements.

---

## Practical Steps

- **Open both pages in your browser, side-by-side.**
- Use browser dev tools to inspect and compare elements.
- Start with the input box: copy the working version’s HTML/CSS to subdomonster.
- Adjust parent containers' overflow settings.
- For icon/resize handle overlap, add spacing or adjust z-index as needed.

---

## Example CSS Fixes

```css
/* For single-line input */
input[type="text"].subdomain-input {
  width: 100%;
  min-height: 2em;
  resize: none;
  overflow: hidden;
}

/* Prevent double scroll bars */
.main-content, .subdomonster-container {
  overflow-y: auto; /* Only on one container */
}
body {
  overflow-y: hidden; /* Or auto, but not both */
}

/* Tag input scroll fix */
.tag-input {
  overflow: hidden;
}

/* Header cells: make room for resize handles */
th {
  position: relative;
  padding-right: 16px; /* or more for icon + handle */
}
```

---

## Next Steps

- Apply these changes in the subdomonster page/template.
